-- Generated by pipeline.py
-- Rows: 755

DO $$
BEGIN
  BEGIN
    CREATE INDEX IF NOT EXISTS "VectorEmbedding_embedding_idx"
      ON "VectorEmbedding" USING ivfflat (embedding vector_cosine_ops);
  EXCEPTION
    WHEN SQLSTATE '22023' THEN
      -- pgvector requires fixed dimensions for ivfflat. Keep data migration green if column is unbounded vector.
      NULL;
  END;
END
$$;

-- The embeddings data insert has been removed for the open source release.
-- The ingested source documents are subject to third-party copyright and are
-- not part of this repository. Build your own corpus with
-- tools/pdf-embeddings-generator.js and load it into the VectorEmbedding table.
