/**
 * Control Scripts Service
 *
 * Generates and writes start.sh/stop.sh scripts to the app directory.
 * These scripts allow operators to manually start/stop the application
 * without needing deploy3 installed.
 *
 * Scripts are regenerated on every deployment with hardcoded paths and
 * compose file configurations from the current deployment.
 */

import { RemoteFileSystem } from '../../infra/file-system';
import { PathResolver } from './path-resolver';
import { DeploymentConfig } from '../../config/deployment-config';
import { Logger } from '../utils/logger';
import {
  CONTAINER_NAME as MAINTENANCE_CONTAINER_NAME,
  CADDY_IMAGE,
} from './maintenance-page';

/**
 * Configuration for ControlScriptsService
 */
export interface ControlScriptsServiceConfig {
  fs: RemoteFileSystem;
  pathResolver: PathResolver;
  logger: Logger;
}

/**
 * ControlScriptsService - Generates start.sh/stop.sh for manual operation
 */
export class ControlScriptsService {
  private readonly fs: RemoteFileSystem;
  private readonly pathResolver: PathResolver;
  private readonly logger: Logger;

  constructor(config: ControlScriptsServiceConfig) {
    this.fs = config.fs;
    this.pathResolver = config.pathResolver;
    this.logger = config.logger;
  }

  /**
   * Write both control scripts to the app directory
   *
   * @param deploymentConfig - The deployment config for compose file list
   */
  writeControlScripts(deploymentConfig: DeploymentConfig): void {
    const stopScript = this.generateStopScript(deploymentConfig);
    const startScript = this.generateStartScript(deploymentConfig);

    const stopPath = this.pathResolver.getControlScriptPath('stop.sh');
    const startPath = this.pathResolver.getControlScriptPath('start.sh');

    this.fs.writeFile(stopPath, stopScript, { silent: true });
    this.fs.chmod(stopPath, '755', { silent: true });

    this.fs.writeFile(startPath, startScript, { silent: true });
    this.fs.chmod(startPath, '755', { silent: true });

    this.logger.info(
      `Control scripts written to ${this.pathResolver.getAppPath()}`
    );
  }

  /**
   * Generate stop.sh script content
   */
  private generateStopScript(deploymentConfig: DeploymentConfig): string {
    const assetsPath = this.pathResolver.getActiveBackendAssetsPath();
    const certCachePath = this.pathResolver.getMaintenanceCertsPath();
    const composeArgs = this.buildComposeArgs(deploymentConfig.composeFiles);

    return `#!/bin/bash
# Auto-generated by deploy3 - do not edit manually
# Stops the application and shows maintenance page
set -e

echo "Stopping application..."
cd "${assetsPath}"
docker compose ${composeArgs} --env-file .env down -v

echo "Starting maintenance page..."
docker rm -f ${MAINTENANCE_CONTAINER_NAME} 2>/dev/null || true

# Only start maintenance if Caddyfile exists (was set up by a previous deployment)
if [ -f "${certCachePath}/Caddyfile" ]; then
  docker run --rm -d --name ${MAINTENANCE_CONTAINER_NAME} \\
    -p 80:80 -p 443:443 -p 443:443/udp \\
    -v "${certCachePath}/Caddyfile:/etc/caddy/Caddyfile:ro" \\
    -v "${certCachePath}/data:/data" \\
    -v "${certCachePath}/config:/config" \\
    ${CADDY_IMAGE} caddy run --config /etc/caddy/Caddyfile --adapter caddyfile
  echo "Maintenance page started"
else
  echo "No Caddyfile found at ${certCachePath}/Caddyfile - skipping maintenance page"
fi

echo "Done"
`;
  }

  /**
   * Generate start.sh script content
   */
  private generateStartScript(deploymentConfig: DeploymentConfig): string {
    const assetsPath = this.pathResolver.getActiveBackendAssetsPath();
    const composeArgs = this.buildComposeArgs(deploymentConfig.composeFiles);

    return `#!/bin/bash
# Auto-generated by deploy3 - do not edit manually
# Stops maintenance page and starts the application
set -e

echo "Stopping maintenance page..."
docker rm -f ${MAINTENANCE_CONTAINER_NAME} 2>/dev/null || true

echo "Starting application..."
cd "${assetsPath}"
docker compose ${composeArgs} --env-file .env up -d

echo "Done"
`;
  }

  /**
   * Build docker compose -f arguments from compose file list
   */
  private buildComposeArgs(composeFiles: string[]): string {
    // Compose files in config are relative to deployment dir,
    // but we run from assets dir, so prefix with deployment/
    return composeFiles.map((file) => `-f "deployment/${file}"`).join(' ');
  }
}
