import path from 'path';
import { logger } from '../../../utils/logger';
import { MergeDeepHelper, JsonObject } from '../merge-deep';

/**
 * Interface for file system operations.
 * Allows the helper to work with both RemoteFileSystem (production) and local FS (tests).
 */
export interface FileSystemLike {
  pathExists(path: string): boolean;
  readFile(path: string): string;
  writeFile(path: string, content: string): void;
  mkdir(path: string): void;
}

/**
 * Optional path overrides for keycloak realm files.
 * All paths are relative to baseDir.
 */
export interface KeycloakRealmPaths {
  /** Base realm template. Default: 'keycloak/templates/realm.json' */
  base?: string;
  /** Staging overlay. Default: 'keycloak/templates/staging.json' */
  staging?: string;
  /** Production overlay. Default: 'keycloak/templates/production.json' */
  production?: string;
  /** Output file location. Default: 'keycloak/import/realm.json' */
  output?: string;
  /** Docker env file for placeholders. Default: '.env' */
  envFile?: string;
}

const DEFAULT_PATHS: Required<KeycloakRealmPaths> = {
  base: 'keycloak/templates/realm.json',
  staging: 'keycloak/templates/staging.json',
  production: 'keycloak/templates/production.json',
  output: 'keycloak/import/realm.json',
  envFile: '.env',
};

/**
 * Helper for building Keycloak realm.json from templates, overlays, and secrets.
 *
 * This helper:
 * 1. Loads the base realm.json template
 * 2. Applies environment-specific overlays (staging.json for staging/production, production.json for production)
 * 3. Merges in secrets from APP_KEYCLOAK_SECRETS
 * 4. Substitutes ${{KEY}} placeholders with values from .env file, which is generated by the deploy process from DEPLOY_DOCKER_ENV
 * 5. Writes the final realm.json to the import directory in the backend assets of the application
 *
 * Provided to maintenance hooks via context.helpers.keycloak.realmMerge
 */
export class KeycloakRealmMergeHelper {
  private readonly mergeDeep = new MergeDeepHelper();

  constructor(private readonly fs: FileSystemLike) {}

  /**
   * Build and write the final keycloak realm.json.
   *
   * @param env - Environment variables (context.env). Must contain DEPLOY_ENVIRONMENT and APP_KEYCLOAK_SECRETS.
   * @param baseDir - Remote base directory containing keycloak/templates/ and .env
   * @param pathOverrides - Optional path overrides for non-standard layouts
   *
   * @throws Error if required env vars are missing, files don't exist, or secrets are invalid JSON
   */
  merge(
    env: Record<string, string>,
    baseDir: string,
    pathOverrides?: KeycloakRealmPaths
  ): void {
    const paths = { ...DEFAULT_PATHS, ...pathOverrides };
    const environment = env['DEPLOY_ENVIRONMENT'];

    // Validate environment
    if (!environment) {
      throw new Error(
        'DEPLOY_ENVIRONMENT is not set. Expected "staging", "production", or "development".'
      );
    }

    const isStaging = environment === 'staging';
    const isProduction = environment === 'production';

    logger.debug(
      `Building keycloak realm.json for environment: ${environment}`
    );

    // Load and parse secrets
    const secretsJson = env['APP_KEYCLOAK_SECRETS'];
    if (!secretsJson) {
      throw new Error(
        'APP_KEYCLOAK_SECRETS is not set. This is required for keycloak realm configuration.'
      );
    }

    let secrets: JsonObject;
    try {
      secrets = JSON.parse(secretsJson) as JsonObject;
    } catch (e) {
      throw new Error(`APP_KEYCLOAK_SECRETS is not valid JSON: ${e}`);
    }

    // Load base realm template
    const basePath = path.join(baseDir, paths.base);
    if (!this.fs.pathExists(basePath)) {
      throw new Error(`Base realm template not found: ${basePath}`);
    }
    const baseRealm = JSON.parse(this.fs.readFile(basePath)) as JsonObject;
    logger.debug(`Loaded base realm from ${paths.base}`);

    // Collect configs to merge in order
    const configsToMerge: JsonObject[] = [baseRealm];

    // Load staging overlay if applicable (staging or production)
    if (isStaging || isProduction) {
      const stagingPath = path.join(baseDir, paths.staging);
      if (this.fs.pathExists(stagingPath)) {
        const stagingOverlay = JSON.parse(
          this.fs.readFile(stagingPath)
        ) as JsonObject;
        configsToMerge.push(stagingOverlay);
        logger.debug(`Loaded staging overlay from ${paths.staging}`);
      } else {
        logger.debug(`Staging overlay not found at ${paths.staging}, skipping`);
      }
    }

    // Load production overlay if applicable
    if (isProduction) {
      const productionPath = path.join(baseDir, paths.production);
      if (this.fs.pathExists(productionPath)) {
        const productionOverlay = JSON.parse(
          this.fs.readFile(productionPath)
        ) as JsonObject;
        configsToMerge.push(productionOverlay);
        logger.debug(`Loaded production overlay from ${paths.production}`);
      } else {
        logger.debug(
          `Production overlay not found at ${paths.production}, skipping`
        );
      }
    }

    // Add secrets last (highest priority)
    configsToMerge.push(secrets);
    logger.debug('Added secrets to merge chain');

    // Merge all configs
    const merged = this.mergeDeep.merge(...configsToMerge);
    logger.debug(`Merged ${configsToMerge.length} config sources`);

    // Load .env file for placeholder substitution
    const envFilePath = path.join(baseDir, paths.envFile);
    if (!this.fs.pathExists(envFilePath)) {
      throw new Error(
        `.env file not found at ${envFilePath}. ` +
          'The orchestrator should write this file before the maintenance hook runs.'
      );
    }
    const envContent = this.fs.readFile(envFilePath);
    const placeholders = this.parseEnvContent(envContent);
    logger.debug(
      `Loaded ${Object.keys(placeholders).length} placeholders from ${
        paths.envFile
      }`
    );

    // Substitute placeholders in merged config
    let mergedJson = JSON.stringify(merged, undefined, 2);
    mergedJson = this.substitutePlaceholders(mergedJson, placeholders);

    // Ensure output directory exists
    const outputPath = path.join(baseDir, paths.output);
    const outputDir = path.dirname(outputPath);
    if (!this.fs.pathExists(outputDir)) {
      this.fs.mkdir(outputDir);
      logger.debug(`Created output directory: ${outputDir}`);
    }

    // Write final realm.json
    this.fs.writeFile(outputPath, mergedJson);
    logger.debug(`Wrote keycloak realm.json to ${paths.output}`);
  }

  /**
   * Parse env file content (KEY=VALUE per line) into a record.
   */
  private parseEnvContent(content: string): Record<string, string> {
    const result: Record<string, string> = {};

    for (const line of content.split('\n')) {
      const trimmed = line.trim();
      if (trimmed.length === 0 || trimmed.startsWith('#')) {
        continue;
      }

      const eqIndex = trimmed.indexOf('=');
      if (eqIndex === -1) {
        continue;
      }

      const key = trimmed.slice(0, eqIndex);
      const value = trimmed.slice(eqIndex + 1).replace(/\r/g, '');
      result[key] = value;
    }

    return result;
  }

  /**
   * Substitute ${{KEY}} placeholders in a string with values from placeholders map.
   * Uses double curly braces to distinguish from docker's ${VAR} syntax.
   */
  private substitutePlaceholders(
    content: string,
    placeholders: Record<string, string>
  ): string {
    let result = content;

    for (const [key, value] of Object.entries(placeholders)) {
      // Build placeholder string without template literal to avoid TS parsing issues
      const placeholder = '${{' + key + '}}';
      if (result.includes(placeholder)) {
        logger.debug('Substituting placeholder ' + placeholder);
        result = result.split(placeholder).join(value);
      }
    }

    // Check for any remaining unsubstituted placeholders
    const remainingPattern = /\$\{\{([A-Za-z_][A-Za-z0-9_]*)\}\}/g;
    const remaining = [...result.matchAll(remainingPattern)];
    if (remaining.length > 0) {
      const unsubstituted = remaining.map((m) => m[1]).join(', ');
      logger.warn(
        'Unsubstituted placeholders remain in realm.json: ' +
          unsubstituted +
          '. ' +
          'These variables were not found in the .env file.'
      );
    }

    return result;
  }
}
