name: 99 - Reusable Deploy Workflow, ignore me

on:
  workflow_call:
    inputs:
      release:
        type: string
        required: true
      target:
        description: 'Target environment'
        type: string
        required: true
      # this must be set to DELETE_USERS for the keycloak import to be skipped
      # just to make it very clear to everybody: This is a very dangerous option
      skip-keycloak-import:
        type: string
        required: false

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - run: echo "Deploying ${{ inputs.target }} with release ${{ inputs.release }} to server ${{ vars.DEPLOY_SERVER }}"

      - uses: actions/checkout@v4
        with:
          ref: dev
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ vars.DEPLOY_SERVER }} >> ~/.ssh/known_hosts
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/deploy_key

      - name: Set env
        run: echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo $RELEASE
      - uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ inputs.release }}
          fileName: '*.zip'

      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Run deploy script v2
        env:
          DEPLOY_SERVER: ${{ vars.DEPLOY_SERVER }}
          DEPLOY_TAG: ${{ inputs.release }}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          DEPLOY_DOCKER_ENV: ${{vars.DEPLOY_DOCKER_ENV}}
          DEPLOY_BACKEND_SECRETS: ${{vars.DEPLOY_BACKEND_SECRETS}}
          DEPLOY_KEYCLOAK_SECRETS: ${{vars.DEPLOY_KEYCLOAK_SECRETS}}
          RESET_KEYCLOAK: ${{inputs.skip-keycloak-import}}
          DEPLOY_CONFIG_SECRETS: ${{vars.DEPLOY_CONFIG_SECRETS}}
        run: node ./tools/deploy2/deploy.js
