name: 99 - Reusable Deploy Workflow, ignore me

on:
  workflow_call:
    inputs:
      release:
        type: string
        required: true
      target:
        description: 'Target environment'
        type: string
        required: true

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    environment: ${{ inputs.target }}
    steps:
      - run: echo "Deploying ${{ inputs.target }} with release ${{ inputs.release }} to server ${{ vars.DEPLOY_SERVER }}"

      - uses: actions/checkout@v4

      - name: Set env
        run: echo "RELEASE=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - run: echo $RELEASE
      - uses: robinraju/release-downloader@v1.8
        with:
          tag: ${{ inputs.release }}
          fileName: '*.zip'

      - name: Run deploy script v3
        shell: bash
        run: |
          set -e

          eval "$(echo '${{ toJSON(vars) }}' | jq -r 'to_entries | map("export \(.key)=\(.value | @sh)") | .[]')"
          eval "$(echo '${{ toJSON(secrets) }}' | jq -r 'to_entries | map("export \(.key)=\(.value | @sh)") | .[]')"

          export DEPLOY_TAG="${{ inputs.release }}"
          echo "Starting deployment with tag: $DEPLOY_TAG"
          cp $DEPLOY_TAG.zip ./tools/deploy3/$DEPLOY_TAG.zip
          cd ./tools/deploy3
          echo "Installing dependencies..."
          npm install
          echo "Running deploy script..."
          npm run deploy
          echo "Deployment completed successfully"

